mod 'puppet-nginx'
mod 'puppetlabs-concat'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-translate'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '3.12.1'
mod 'puppetlabs-apt', '7.6.0'
mod 'puppetlabs-reboot', '3.0.0'
